spring.application.name=kcg-spring
spring.datasource.url=jdbc:postgresql://db.kcglobed.com:5432/KCGSpring
spring.datasource.username=dbadmin
spring.datasource.password=KCG@2026Aug
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081